# -*- coding: utf-8 -*-
"""escape character

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JxLt_iOGXDOE3OtF97tcsTqE9f4MkW_p
"""

print ('dia berkata : "pergilah!"')

print ("Aku menimpali: \"apakah kau ingin aku 'angkat kaki'?!\" ")

print (" \\(^_^)/ (\\ -_-/) ")