# -*- coding: utf-8 -*-
"""Mo0dul dan packages.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-95ivWOqJ_xOSb7mqV6Xp9hayZwrnbxt
"""

* Nama : prabs
* NPM : 150000000

import matematika

print(matematika.pi)

print("Nilai PI:", matematika.pi)
print("Luas Lingkaran (r=21):", matematika.luas_lingkaran(radius=21))
print("Luas Persegi (s=12):", matematika.luas_persegi(sisi=12))

from matematika import luas_persegi as lp
from matematika import luas_lingkaran as ll

print("Luas Persegi (s=10):", lp(10))
print("Luas Lingkaran (R=7):", ll(7))

from luas.segitiga import luas_segitiga

print("Luas Segitiga (alas=10, tinggi=5):", luas_segitiga(10,5))

import math
import datetime

waktu_sekarang = datetime.datetime.now()
print("Tanggal dan waktu saat ini:", waktu_sekarang)

print("Nilai PI dari modul math:", math.pi)