# -*- coding: utf-8 -*-
"""tugas kelompok.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AqBGzCCY_mtVn2tYcGY7K9STYU_KbMbG
"""

# Data mentah
data = "#001-wahyu aji-informatika-python,java,php-aktif"

# Hilangkan tanda #
data_bersih = data.replace("#", "")

# Pisahkan berdasarkan tanda -
bagian = data_bersih.split("-")

# Ambil data
id_pendaftar = bagian[0]
nama_lengkap = bagian[1].title()
program_studi = bagian[2].upper()
skill_list = bagian[3].split(",")
status_akun = bagian[4].capitalize()

# Gabungkan skill
skill_dikuasai = " & ".join(skill_list)

# Hitung total skill
total_skill = len(skill_list)

# Tampilkan hasil
print("Data Mentah: '", data, "'")
print("======================================")
print("         HASIL VERIFIKASI DATA")
print("======================================")
print(f"ID Pendaftar   : {id_pendaftar} (3 digit)")
print(f"Nama Lengkap   : {nama_lengkap}")
print(f"Program Studi  : {program_studi}")
print(f"Skill Dikuasai : {skill_dikuasai}")
print(f"Total Skill    : {total_skill}")
print(f"Status Akun    : {status_akun}")
print("======================================")