# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mg3FP3c3ok5khfcBKaeBc2LAE1h2k4g5

**format specifiers**
"""

template = 'Halo, saya %s dari %s'

print (template % ('Lendis Fabri', 'indonesia'))

"""**fungsi format**"""

template = 'halo, saya {nama} dari {asal}'
template_2 = 'saya suka makan {} dan minum {}'

print (template. format(nama= 'lendes fabri', asal= 'indonesia'))
print (template_2.format('nasi goreng', 'teh pucuk'))

"""**string interpolation**"""

nama = 'lendis fabri'
asal = 'indonesia'

print (f'perkenalkan saya {nama} dari {asal}')

print ('_'.join(['aku', 'suka', 'python']))

print ('halo selamat pagi!'.upper())
print ('halo  selamat pag!'.upper())

print ('APA KABAR!'.lower())
print ('LAGI DIMANA?'.lower())

print ('daun tidak pernah membenci angin'.title())

print ('indOnesia Adalah negara kepulauan'.swapcase())
print ('aku cinta neGriku'.swapcase())

angka = '12345'

print ('Indeks angka 3:', angka.find ('3'))
print ('Indeks angka 45:', angka.find ('45'))
print ('Indeks angka 35:', angka.find ('35'))

ibu_kota = 'jakarta'

print (ibu_kota.replace ('a', 'i'))
print (ibu_kota.replace ('kar', '@'))

paragraf = 'baru baru ini telah ditemukan sebuah meteor di suatu sungai'
x = paragraf.count ('di')

print (f'kata "di" muncul sebanyak {x}')