# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UPMpr42KeXw6pOKjEzZnJCBFVH8ivZUC

**string**
"""

nama = 'trie intan kesuma'
asal = 'indonesia'

print(nama+asal)

print("halo, nama saya", nama)

print("halo, nama saya", nama, "asal saya dari", asal)

data_lengkap = nama + asal

print(data_lengkap)

data_lengkap_fix_final = nama + asal

print(data_lengkap_fix_final)

"""**string + non string**"""

asal_kota = "bandar lampung"
kode_pos = 35144

asal_kota_kode_pos = asal_kota + str(kode_pos)
print(asal_kota_kode_pos)

asal_kota_x3 = asal_kota * 3
print(asal_kota_x3)